# Merge yearly .hdf files into input & output .csv files
## Do not use 2019 (since the output is all null)

In [1]:
print('Imports')
import glob
import os
import pandas as pd

Imports

In [2]:
# Input to .csv
print('Input files')
path = '/home/jovyan/Arctic/Vegetation_in_Troms_and_Finnmark/data/'
x_filename = 'x_mean_tp4_2*.hdf'
file_list = glob.glob(os.path.join(path, x_filename))
file_list.sort()
file_list

input_filename = os.path.join(path, 'input_mean_tp4.csv')

for file_name in file_list[0:-1]:
    print(file_name)
    df = pd.read_hdf(file_name)
    print(df)
    df = df.drop(columns=['lon_lat'])
    if (file_name == file_list[0]):
         df.to_csv(input_filename, header=True, index=None, sep=',')
    else:
        # Append to file
         df.to_csv(input_filename, mode='a', header=None, index=None, sep=',')

Input files
/home/jovyan/Arctic/Vegetation_in_Troms_and_Finnmark/data/x_mean_tp4_2015.hdf
        lon_lat  Lichen_mean    N     t2m_0     t2m_1     t2m_2     t2m_3  \
0    2459.07055     0.040000   25  0.999619  0.999572  0.999950  0.999674
1    2419.06875     0.010000    3  0.992204  0.991964  0.991303  0.990271
2    2609.06994     0.148020  101  0.992969  0.992618  0.992516  0.991884
3    2409.06994     0.046818   22  0.994447  0.994460  0.994365  0.994023
4    2419.06994     0.020000    3  0.994371  0.994398  0.994296  0.993945
..          ...          ...  ...       ...       ...       ...       ...
592  1869.06855     0.091355  310  0.969183  0.969292  0.968639  0.968304
593  2469.07065     0.058333   12  1.001587  1.001416  1.001776  1.001554
594  2509.07065     0.025000   53  1.002270  1.002095  1.002488  1.002333
595  3009.07044     0.039722   36  0.994939  0.994101  0.993448  0.993124
596  2569.06925     0.010000    4  0.995663  0.995232  0.994631  0.993752

        t2m_4     t2m_5     t2m_6  ...   tp_8750   tp_8751   tp_8752  \
0    0.999481  0.998745  0.997950  ...  4.010188  4.449581  4.961025
1    0.989013  0.987411  0.985844  ...  3.128518  3.142485  3.150244
2    0.991230  0.990178  0.988565  ...  3.847687  4.187763  4.283977
3    0.993486  0.992993  0.992268  ...  3.839041  3.874069  3.894243
4    0.993382  0.992840  0.992066  ...  3.884266  3.924171  3.945010
..        ...       ...       ...  ...       ...       ...       ...
592  0.968724  0.970215  0.971178  ...  6.387392  6.710176  6.943839
593  1.001372  1.000684  0.999936  ...  3.831726  4.380191  5.203334
594  1.002106  1.001316  1.000577  ...  3.538205  4.172688  4.888753
595  0.992907  0.992707  0.991753  ...  0.671061  1.177185  1.743164
596  0.992698  0.991092  0.989525  ...  3.797363  3.825296  3.829287

      tp_8753   tp_8754   tp_8755   tp_8756   tp_8757   tp_8758   tp_8759
0    5.224617  5.248782  5.509491  5.573116  5.614573  5.655586  5.729631
1    3.150244  3.150244  3.150244  3.150244  3.150466  3.151574  3.153569
2    4.316123  4.324769  4.369107  4.385956  4.399257  4.414554  4.436723
3    3.901115  3.901558  3.906879  3.909096  3.912421  3.919959  3.933926
4    3.952769  3.953213  3.958977  3.961194  3.964741  3.972278  3.984250
..        ...       ...       ...       ...       ...       ...       ...
592  7.048921  7.157992  7.229378  7.283250  7.318942  7.343106  7.376803
593  5.655808  5.705024  6.181218  6.336624  6.453899  6.548562  6.683128
594  5.273611  5.330142  5.932923  6.241740  6.568292  6.790871  7.026751
595  2.138885  2.397821  2.716836  3.070435  3.369498  3.633754  3.954321
596  3.831282  3.831504  3.831947  3.832169  3.832390  3.833277  3.834829

[597 rows x 17523 columns]
/home/jovyan/Arctic/Vegetation_in_Troms_and_Finnmark/data/x_mean_tp4_2016.hdf
        lon_lat  Lichen_mean    N     t2m_0     t2m_1     t2m_2     t2m_3  \
0    2459.07055     0.078571    7  0.978875  0.981369  0.983563  0.984518
1    2419.06875     0.016000   60  0.969349  0.969494  0.969165  0.969724
2    2609.06994     0.041863  451  0.972576  0.974156  0.974943  0.974905
3    2679.06975     0.015952   42  0.976658  0.978183  0.979055  0.978469
4    2479.06975     0.023279    3  0.972951  0.969267  0.969764  0.972090
..          ...          ...  ...       ...       ...       ...       ...
805  2469.07065     0.043636   25  0.985427  0.986960  0.987954  0.987988
806  2609.06915     0.021538   26  0.968560  0.970472  0.973321  0.974956
807  3009.07044     0.028434   52  0.989317  0.988176  0.987446  0.986523
808  2229.07055     0.043158  171  1.000333  0.999317  0.998259  0.997866
809  2569.06925     0.010000    4  0.971610  0.973343  0.976161  0.978176

        t2m_4     t2m_5     t2m_6  ...   tp_8750   tp_8751   tp_8752  \
0    0.985434  0.985409  0.985203  ...  0.018844  0.019952  0.023056
1    0.970705  0.971251  0.972378  ...  0.503684  0.503905  0.504571
2    0.974499  0.974229  0.973330  ...  0.191763  0.192428  0.193093
3    0.977530  0.976536  0.974657  ...  0.139666  0.140552  0.140996
4    0.973372  0.974340  0.974178  ...  0.146317  0.146760  0.146760
..        ...       ...       ...  ...       ...       ...       ...
805  0.988045  0.987673  0.987284  ...  0.026602  0.027711  0.031923
806  0.975813  0.976993  0.976179  ...  0.294185  0.294407  0.294407
807  0.986290  0.985820  0.985210  ...  0.121709  0.121930  0.122374
808  0.997393  0.997191  0.997298  ...  0.474421  0.567088  0.677269
809  0.979525  0.980823  0.980674  ...  0.266030  0.266030  0.266474

      tp_8753   tp_8754   tp_8755   tp_8756   tp_8757   tp_8758   tp_8759
0    0.025051  0.025716  0.027268  0.028598  0.029485  0.030372  0.030815
1    0.505014  0.506788  0.508340  0.510778  0.511665  0.512995  0.514990
2    0.193315  0.193315  0.193758  0.193758  0.193980  0.194202  0.194645
3    0.141439  0.141661  0.142105  0.142991  0.144099  0.145430  0.146317
4    0.146982  0.146982  0.147203  0.147425  0.147425  0.147647  0.148312
..        ...       ...       ...       ...       ...       ...       ...
805  0.035692  0.038352  0.043451  0.048107  0.049437  0.051432  0.052541
806  0.294850  0.295515  0.296845  0.299062  0.300836  0.303275  0.305269
807  0.122595  0.122817  0.123039  0.123260  0.123704  0.123925  0.124369
808  0.769050  0.821147  0.922017  1.051263  1.161888  1.194920  1.196472
809  0.266474  0.266917  0.267582  0.268690  0.269799  0.271129  0.272459

[810 rows x 17523 columns]
/home/jovyan/Arctic/Vegetation_in_Troms_and_Finnmark/data/x_mean_tp4_2017.hdf
        lon_lat  Lichen_mean    N     t2m_0     t2m_1     t2m_2     t2m_3  \
0    2459.07055     0.088571   48  0.953982  0.952923  0.951692  0.950705
1    2419.06875     0.022000   60  0.958027  0.957874  0.957769  0.957106
2    2209.06865     0.053500    5  0.942481  0.942735  0.944099  0.944774
3    2609.06994     0.076315  464  0.954567  0.955162  0.955861  0.957046
4    2679.06975     0.041429   42  0.962349  0.964439  0.965917  0.967586
..          ...          ...  ...       ...       ...       ...       ...
841  2629.06915     0.020000    2  0.972913  0.973878  0.974491  0.974542
842  1869.06855     0.092944  958  0.940225  0.940509  0.940724  0.941148
843  2469.07065     0.057955   44  0.962227  0.961526  0.960439  0.959363
844  2609.06915     0.063462   26  0.971997  0.972786  0.973246  0.973093
845  2569.06925     0.020000  292  0.967818  0.968451  0.968748  0.968435

        t2m_4     t2m_5     t2m_6  ...   tp_8750   tp_8751   tp_8752  \
0    0.949928  0.949478  0.949375  ...  0.708749  0.712740  0.717838
1    0.957885  0.959207  0.961271  ...  0.027489  0.105525  0.289973
2    0.946615  0.947754  0.949992  ...  0.159396  0.419219  0.683033
3    0.957146  0.957188  0.956824  ...  0.070054  0.076483  0.090007
4    0.968213  0.967807  0.967550  ...  0.041234  0.046112  0.060743
..        ...       ...       ...  ...       ...       ...       ...
841  0.974067  0.973689  0.973971  ...  0.018622  0.030815  0.070941
842  0.940640  0.941270  0.941135  ...  0.628275  0.848415  1.051928
843  0.958484  0.957501  0.956873  ...  0.936206  0.938644  0.942413
844  0.972527  0.972296  0.972636  ...  0.015075  0.028155  0.071606
845  0.967801  0.967799  0.968176  ...  0.017957  0.031923  0.075153

      tp_8753   tp_8754   tp_8755   tp_8756   tp_8757   tp_8758   tp_8759
0    0.726263  0.747989  0.762620  0.787006  0.829571  0.890315  0.965025
1    0.488609  0.633152  0.858613  1.002491  1.113559  1.229282  1.316407
2    0.846642  0.929776  1.008477  1.055919  1.090947  1.123535  1.155459
3    0.128803  0.202626  0.337193  0.502797  0.654878  0.763286  0.849967
4    0.103530  0.185113  0.401262  0.675939  0.928668  1.115997  1.266748
..        ...       ...       ...       ...       ...       ...       ...
841  0.158731  0.315024  0.548466  0.769715  0.999388  1.209774  1.357642
842  1.235711  1.401315  1.643181  1.933820  2.287197  2.766717  3.312301
843  0.948620  0.965912  0.978105  1.001161  1.053037  1.130186  1.205783
844  0.163165  0.319901  0.542480  0.751092  0.971898  1.173194  1.312860
845  0.161170  0.307043  0.516542  0.723159  0.943743  1.127304  1.244357

[846 rows x 17523 columns]
/home/jovyan/Arctic/Vegetation_in_Troms_and_Finnmark/data/x_mean_tp4_2018.hdf
        lon_lat  Lichen_mean    N     t2m_0     t2m_1     t2m_2     t2m_3  \
0    2419.06875     0.032000  688  0.973603  0.973115  0.972207  0.970714
1    2609.06994     0.094125  463  0.955466  0.955622  0.955690  0.955431
2    2679.06975     0.077857   42  0.962970  0.963299  0.963567  0.963265
3    2479.06975     0.065574   61  0.956112  0.955335  0.954141  0.953363
4    2279.06925     0.050449  178  0.963809  0.963663  0.963283  0.962984
..          ...          ...  ...       ...       ...       ...       ...
777  2629.06915     0.030000    2  0.970166  0.969656  0.969405  0.968324
778  1869.06855     0.120547  951  0.967437  0.967310  0.966509  0.966239
779  2579.07105     0.051200  228  0.990227  0.990582  0.991465  0.992337
780  2609.06915     0.084615   26  0.970596  0.970117  0.969818  0.968757
781  2569.06925     0.020000    4  0.970403  0.970059  0.969700  0.968675

        t2m_4     t2m_5     t2m_6  ...   tp_8750   tp_8751   tp_8752  \
0    0.968611  0.967022  0.965296  ...  0.042786  0.046777  0.049880
1    0.957508  0.961315  0.965759  ...  0.307708  0.346726  0.387739
2    0.964566  0.967803  0.971715  ...  0.242753  0.255611  0.266695
3    0.953724  0.954732  0.958189  ...  0.221914  0.257162  0.281992
4    0.962194  0.962132  0.962165  ...  0.139444  0.160948  0.178462
..        ...       ...       ...  ...       ...       ...       ...
777  0.966665  0.966376  0.967062  ...  0.119935  0.124812  0.127694
778  0.965688  0.965218  0.964373  ...  1.724764  1.948230  2.181006
779  0.991467  0.991347  0.990251  ...  2.783122  2.906383  2.953603
780  0.966935  0.966605  0.967310  ...  0.121044  0.127029  0.130133
781  0.966705  0.966589  0.967874  ...  0.139887  0.148533  0.153854

      tp_8753   tp_8754   tp_8755   tp_8756   tp_8757   tp_8758   tp_8759
0    0.052319  0.054314  0.055645  0.057196  0.058970  0.060078  0.061409
1    0.450478  0.540928  0.654878  0.813388  0.907607  0.998057  1.042839
2    0.280884  0.295737  0.327660  0.400597  0.441389  0.463780  0.484397
3    0.305269  0.332981  0.356703  0.402814  0.450478  0.487722  0.515212
4    0.197527  0.218588  0.239427  0.257606  0.271794  0.283765  0.291968
..        ...       ...       ...       ...       ...       ...       ...
777  0.129911  0.131463  0.132793  0.135232  0.139000  0.144321  0.149420
778  2.412896  2.659639  2.767382  2.810612  2.840097  2.877784  2.949169
779  2.972669  2.985527  3.016785  3.057798  3.098368  3.126301  3.150244
780  0.132793  0.134345  0.136119  0.138557  0.142326  0.147203  0.150528
781  0.158066  0.161391  0.163830  0.168042  0.173806  0.180014  0.184891

[782 rows x 17523 columns]

In [3]:
# Output to .csv
print('Output files')
y_filename = 'y_mean_tp4_2*.hdf'
file_list = glob.glob(os.path.join(path, y_filename))
file_list.sort()
file_list

output_filename = os.path.join(path, 'output_mean_tp4.csv')

for file_name in file_list[0:-1]:
    print(file_name)
    dg = pd.read_hdf(file_name)
    print(dg)
    dg = dg.reset_index()
    dg = dg.drop(columns=['lon_lat'])
    if (file_name == file_list[0]):
         dg.to_csv(output_filename, header=True, index=None, sep=',')
    else:
        # Append to file
         dg.to_csv(output_filename, mode='a',  header=None, index=None, sep=',')

Output files
/home/jovyan/Arctic/Vegetation_in_Troms_and_Finnmark/data/y_mean_tp4_2015.hdf
            new_Lichen_mean  new_N
lon_lat
2459.07055         0.078571    7.0
2419.06875         0.016000    8.0
2609.06994         0.041863  451.0
2409.06994         0.092286   35.0
2419.06994         0.130000    3.0
...                     ...    ...
1869.06855         0.061455  742.0
2469.07065         0.043636  224.0
2509.07065         0.027500   52.0
3009.07044         0.028434  171.0
2569.06925         0.010000  292.0

[597 rows x 2 columns]
/home/jovyan/Arctic/Vegetation_in_Troms_and_Finnmark/data/y_mean_tp4_2016.hdf
            new_Lichen_mean  new_N
lon_lat
2459.07055         0.088571     48
2419.06875         0.022000      5
2609.06994         0.076315     42
2679.06975         0.041429    464
2479.06975         0.040820     35
...                     ...    ...
2469.07065         0.057955    200
2609.06915         0.063462      7
3009.07044         0.044578    169
2229.07055         0.060000     83
2569.06925         0.020000      4

[810 rows x 2 columns]
/home/jovyan/Arctic/Vegetation_in_Troms_and_Finnmark/data/y_mean_tp4_2017.hdf
            new_Lichen_mean  new_N
lon_lat
2459.07055         0.100000      7
2419.06875         0.032000     60
2209.06865         0.079667      5
2609.06994         0.094125    463
2679.06975         0.077857     42
...                     ...    ...
2629.06915         0.030000      2
1869.06855         0.120547    951
2469.07065         0.100455     25
2609.06915         0.084615     26
2569.06925         0.020000      4

[846 rows x 2 columns]
/home/jovyan/Arctic/Vegetation_in_Troms_and_Finnmark/data/y_mean_tp4_2018.hdf
            new_Lichen_mean  new_N
lon_lat
2419.06875         0.038000   97.0
2609.06994         0.103399  459.0
2679.06975         0.091667   42.0
2479.06975         0.075738    3.0
2279.06925         0.092716   30.0
...                     ...    ...
2629.06915         0.030000  928.0
1869.06855         0.140291    2.0
2579.07105         0.075200   25.0
2609.06915         0.108846   26.0
2569.06925         0.030000    4.0

[782 rows x 2 columns]

In [4]:
print('Finished!')

Finished!