# Merge yearly .hdf files into input & output .csv files

In [1]:
print('Imports')
import glob
import os
import pandas as pd

Imports

In [2]:
# Input to .csv
print('Input files')
path = '/home/ubuntu/data/'
x_filename = 'x_mean_tp1_2*.hdf'
file_list = glob.glob(os.path.join(path, x_filename))
file_list.sort()
file_list

input_filename = os.path.join(path, 'input_mean_tp1.csv')

for file_name in file_list:
    print(file_name)
    df = pd.read_hdf(file_name)
    print(df)
    df = df.drop(columns=['lon_lat'])
    if (file_name == file_list[0]):
         df.to_csv(input_filename, header=True, index=None, sep=',')
    else:
        # Append to file
         df.to_csv(input_filename, mode='a', header=None, index=None, sep=',')

Input files
/home/ubuntu/data/x_mean_tp1_2015.hdf
        lon_lat  Lichen_mean    N     t2m_0     t2m_1     t2m_2     t2m_3  \
0    2459.07055     0.231587  189  0.999619  0.999572  0.999950  0.999674
1    1729.06844     0.050000    3  0.983679  0.985862  0.987675  0.988554
2    1879.06925     0.173182    3  0.976210  0.975702  0.976749  0.978141
3    2419.06875     0.010000   10  0.992204  0.991964  0.991303  0.990271
4    2609.06994     0.209886   26  0.992969  0.992618  0.992516  0.991884
..          ...          ...  ...       ...       ...       ...       ...
734  2469.07065     0.181210   29  1.001587  1.001416  1.001776  1.001554
735  2509.07065     0.232542   59  1.002270  1.002095  1.002488  1.002333
736  3009.07044     0.107236   79  0.994939  0.994101  0.993448  0.993124
737  2879.06965     0.170000  634  0.994005  0.993699  0.993080  0.992594
738  2569.06925     0.035556    9  0.995663  0.995232  0.994631  0.993752

        t2m_4     t2m_5     t2m_6  ...   tp_8750   tp_8751    tp_8752  \
0    0.999481  0.998745  0.997950  ...  4.010188  4.449581   4.961025
1    0.986894  0.984915  0.984358  ...  9.013112  9.828053  10.351024
2    0.978149  0.977464  0.977317  ...  6.585141  6.711505   6.775796
3    0.989013  0.987411  0.985844  ...  3.128518  3.142485   3.150244
4    0.991230  0.990178  0.988565  ...  3.847687  4.187763   4.283977
..        ...       ...       ...  ...       ...       ...        ...
734  1.001372  1.000684  0.999936  ...  3.831726  4.380191   5.203334
735  1.002106  1.001316  1.000577  ...  3.538205  4.172688   4.888753
736  0.992907  0.992707  0.991753  ...  0.671061  1.177185   1.743164
737  0.991553  0.990788  0.989004  ...  2.360355  3.264194   3.634641
738  0.992698  0.991092  0.989525  ...  3.797363  3.825296   3.829287

       tp_8753    tp_8754    tp_8755    tp_8756    tp_8757    tp_8758  \
0     5.224617   5.248782   5.509491   5.573116   5.614573   5.655586
1    10.729674  11.102118  11.354179  11.582746  11.697359  11.796677
2     6.834988   6.931202   6.963791   7.005912   7.037393   7.054019
3     3.150244   3.150244   3.150244   3.150244   3.150466   3.151574
4     4.316123   4.324769   4.369107   4.385956   4.399257   4.414554
..         ...        ...        ...        ...        ...        ...
734   5.655808   5.705024   6.181218   6.336624   6.453899   6.548562
735   5.273611   5.330142   5.932923   6.241740   6.568292   6.790871
736   2.138885   2.397821   2.716836   3.070435   3.369498   3.633754
737   3.755907   3.818202   3.991565   4.162490   4.300161   4.371767
738   3.831282   3.831504   3.831947   3.832169   3.832390   3.833277

       tp_8759
0     5.729631
1    11.929029
2     7.060227
3     3.153569
4     4.436723
..         ...
734   6.683128
735   7.026751
736   3.954321
737   4.428299
738   3.834829

[739 rows x 17523 columns]
/home/ubuntu/data/x_mean_tp1_2016.hdf
        lon_lat  Lichen_mean    N     t2m_0     t2m_1     t2m_2     t2m_3  \
0    2459.07055     0.274750  240  0.978875  0.981369  0.983563  0.984518
1    1729.06844     0.030000    3  0.981968  0.980506  0.978005  0.977333
2    2419.06875     0.016000    8  0.969349  0.969494  0.969165  0.969724
3    2609.06994     0.070080   48  0.972576  0.974156  0.974943  0.974905
4    2679.06975     0.039792   17  0.976658  0.978183  0.979055  0.978469
..          ...          ...  ...       ...       ...       ...       ...
889  2609.06915     0.038065   12  0.968560  0.970472  0.973321  0.974956
890  2229.07055     0.136864    6  1.000333  0.999317  0.998259  0.997866
891  3009.07044     0.077252   20  0.989317  0.988176  0.987446  0.986523
892  2879.06965     0.230000  317  0.986144  0.984307  0.983566  0.982130
893  2569.06925     0.023333    5  0.971610  0.973343  0.976161  0.978176

        t2m_4     t2m_5     t2m_6  ...   tp_8750   tp_8751   tp_8752  \
0    0.985434  0.985409  0.985203  ...  0.018844  0.019952  0.023056
1    0.976503  0.975367  0.977925  ...  0.877679  0.877900  0.877900
2    0.970705  0.971251  0.972378  ...  0.503684  0.503905  0.504571
3    0.974499  0.974229  0.973330  ...  0.191763  0.192428  0.193093
4    0.977530  0.976536  0.974657  ...  0.139666  0.140552  0.140996
..        ...       ...       ...  ...       ...       ...       ...
889  0.975813  0.976993  0.976179  ...  0.294185  0.294407  0.294407
890  0.997393  0.997191  0.997298  ...  0.474421  0.567088  0.677269
891  0.986290  0.985820  0.985210  ...  0.121709  0.121930  0.122374
892  0.981269  0.981444  0.981054  ...  0.194202  0.195311  0.195754
893  0.979525  0.980823  0.980674  ...  0.266030  0.266030  0.266474

      tp_8753   tp_8754   tp_8755   tp_8756   tp_8757   tp_8758   tp_8759
0    0.025051  0.025716  0.027268  0.028598  0.029485  0.030372  0.030815
1    0.877900  0.877900  0.877900  0.877900  0.877900  0.877900  0.877900
2    0.505014  0.506788  0.508340  0.510778  0.511665  0.512995  0.514990
3    0.193315  0.193315  0.193758  0.193758  0.193980  0.194202  0.194645
4    0.141439  0.141661  0.142105  0.142991  0.144099  0.145430  0.146317
..        ...       ...       ...       ...       ...       ...       ...
889  0.294850  0.295515  0.296845  0.299062  0.300836  0.303275  0.305269
890  0.769050  0.821147  0.922017  1.051263  1.161888  1.194920  1.196472
891  0.122595  0.122817  0.123039  0.123260  0.123704  0.123925  0.124369
892  0.196419  0.196862  0.197084  0.197749  0.198857  0.201296  0.203291
893  0.266474  0.266917  0.267582  0.268690  0.269799  0.271129  0.272459

[894 rows x 17523 columns]
/home/ubuntu/data/x_mean_tp1_2017.hdf
        lon_lat  Lichen_mean     N     t2m_0     t2m_1     t2m_2     t2m_3  \
0    2459.07055     0.083000    10  0.953982  0.952923  0.951692  0.950705
1    1729.06844     0.020000    77  0.946229  0.947272  0.950758  0.955275
2    2419.06875     0.022000     5  0.958027  0.957874  0.957769  0.957106
3    2209.06865     0.057200    75  0.942481  0.942735  0.944099  0.944774
4    2609.06994     0.088329   700  0.954567  0.955162  0.955861  0.957046
..          ...          ...   ...       ...       ...       ...       ...
911  2629.06915     0.012500     8  0.972913  0.973878  0.974491  0.974542
912  1869.06855     0.115991  1407  0.940225  0.940509  0.940724  0.941148
913  2469.07065     0.156992   123  0.962227  0.961526  0.960439  0.959363
914  2609.06915     0.108696    46  0.971997  0.972786  0.973246  0.973093
915  2569.06925     0.023333   328  0.967818  0.968451  0.968748  0.968435

        t2m_4     t2m_5     t2m_6  ...   tp_8750   tp_8751   tp_8752  \
0    0.949928  0.949478  0.949375  ...  0.708749  0.712740  0.717838
1    0.960106  0.963649  0.966279  ...  0.768606  0.989633  1.248126
2    0.957885  0.959207  0.961271  ...  0.027489  0.105525  0.289973
3    0.946615  0.947754  0.949992  ...  0.159396  0.419219  0.683033
4    0.957146  0.957188  0.956824  ...  0.070054  0.076483  0.090007
..        ...       ...       ...  ...       ...       ...       ...
911  0.974067  0.973689  0.973971  ...  0.018622  0.030815  0.070941
912  0.940640  0.941270  0.941135  ...  0.628275  0.848415  1.051928
913  0.958484  0.957501  0.956873  ...  0.936206  0.938644  0.942413
914  0.972527  0.972296  0.972636  ...  0.015075  0.028155  0.071606
915  0.967801  0.967799  0.968176  ...  0.017957  0.031923  0.075153

      tp_8753   tp_8754   tp_8755   tp_8756   tp_8757   tp_8758   tp_8759
0    0.726263  0.747989  0.762620  0.787006  0.829571  0.890315  0.965025
1    1.546302  1.938919  2.472531  3.150466  4.088223  5.254102  6.308691
2    0.488609  0.633152  0.858613  1.002491  1.113559  1.229282  1.316407
3    0.846642  0.929776  1.008477  1.055919  1.090947  1.123535  1.155459
4    0.128803  0.202626  0.337193  0.502797  0.654878  0.763286  0.849967
..        ...       ...       ...       ...       ...       ...       ...
911  0.158731  0.315024  0.548466  0.769715  0.999388  1.209774  1.357642
912  1.235711  1.401315  1.643181  1.933820  2.287197  2.766717  3.312301
913  0.948620  0.965912  0.978105  1.001161  1.053037  1.130186  1.205783
914  0.163165  0.319901  0.542480  0.751092  0.971898  1.173194  1.312860
915  0.161170  0.307043  0.516542  0.723159  0.943743  1.127304  1.244357

[916 rows x 17523 columns]
/home/ubuntu/data/x_mean_tp1_2018.hdf
        lon_lat  Lichen_mean     N     t2m_0     t2m_1     t2m_2     t2m_3  \
0    1729.06844     0.023000    10  0.985793  0.985725  0.983523  0.982341
1    2419.06875     0.077273   149  0.973603  0.973115  0.972207  0.970714
2    2679.06975     0.161037     9  0.962970  0.963299  0.963567  0.963265
3    2609.06994     0.114768   164  0.955466  0.955622  0.955690  0.955431
4    2479.06975     0.104222    90  0.956112  0.955335  0.954141  0.953363
..          ...          ...   ...       ...       ...       ...       ...
849  2629.06915     0.015000     8  0.970166  0.969656  0.969405  0.968324
850  1869.06855     0.137367  1238  0.967437  0.967310  0.966509  0.966239
851  2579.07105     0.054444   812  0.990227  0.990582  0.991465  0.992337
852  2609.06915     0.113125    48  0.970596  0.970117  0.969818  0.968757
853  2569.06925     0.076667   366  0.970403  0.970059  0.969700  0.968675

        t2m_4     t2m_5     t2m_6  ...   tp_8750   tp_8751   tp_8752  \
0    0.980661  0.979265  0.977570  ...  1.850020  1.954437  2.081023
1    0.968611  0.967022  0.965296  ...  0.042786  0.046777  0.049880
2    0.964566  0.967803  0.971715  ...  0.242753  0.255611  0.266695
3    0.957508  0.961315  0.965759  ...  0.307708  0.346726  0.387739
4    0.953724  0.954732  0.958189  ...  0.221914  0.257162  0.281992
..        ...       ...       ...  ...       ...       ...       ...
849  0.966665  0.966376  0.967062  ...  0.119935  0.124812  0.127694
850  0.965688  0.965218  0.964373  ...  1.724764  1.948230  2.181006
851  0.991467  0.991347  0.990251  ...  2.783122  2.906383  2.953603
852  0.966935  0.966605  0.967310  ...  0.121044  0.127029  0.130133
853  0.966705  0.966589  0.967874  ...  0.139887  0.148533  0.153854

      tp_8753   tp_8754   tp_8755   tp_8756   tp_8757   tp_8758   tp_8759
0    2.194308  2.298725  2.379199  2.466324  2.508224  2.571628  2.682917
1    0.052319  0.054314  0.055645  0.057196  0.058970  0.060078  0.061409
2    0.280884  0.295737  0.327660  0.400597  0.441389  0.463780  0.484397
3    0.450478  0.540928  0.654878  0.813388  0.907607  0.998057  1.042839
4    0.305269  0.332981  0.356703  0.402814  0.450478  0.487722  0.515212
..        ...       ...       ...       ...       ...       ...       ...
849  0.129911  0.131463  0.132793  0.135232  0.139000  0.144321  0.149420
850  2.412896  2.659639  2.767382  2.810612  2.840097  2.877784  2.949169
851  2.972669  2.985527  3.016785  3.057798  3.098368  3.126301  3.150244
852  0.132793  0.134345  0.136119  0.138557  0.142326  0.147203  0.150528
853  0.158066  0.161391  0.163830  0.168042  0.173806  0.180014  0.184891

[854 rows x 17523 columns]

In [4]:
# Output to .csv
print('Output files')
y_filename = 'y_mean_tp1_2*.hdf'
file_list = glob.glob(os.path.join(path, y_filename))
file_list.sort()
file_list

output_filename = os.path.join(path, 'output_mean_tp1.csv')

for file_name in file_list:
    print(file_name)
    dg = pd.read_hdf(file_name)
    print(dg)
    dg = dg.reset_index()
    dg = dg.drop(columns=['lon_lat'])
    if (file_name == file_list[0]):
         dg.to_csv(output_filename, header=True, index=None, sep=',')
    else:
        # Append to file
         dg.to_csv(output_filename, mode='a',  header=None, index=None, sep=',')

Output files
/home/ubuntu/data/y_mean_tp1_2015.hdf
            new_Lichen_mean  new_N
lon_lat
2459.07055         0.274750  240.0
1729.06844         0.030000    3.0
1879.06925              NaN    NaN
2419.06875         0.016000   60.0
2609.06994         0.070080  502.0
...                     ...    ...
2469.07065         0.151987  156.0
2509.07065         0.139412  102.0
3009.07044         0.077252  131.0
2879.06965         0.230000  317.0
2569.06925         0.023333  491.0

[739 rows x 2 columns]
/home/ubuntu/data/y_mean_tp1_2016.hdf
            new_Lichen_mean  new_N
lon_lat
2459.07055         0.083000   10.0
1729.06844         0.020000  485.0
2419.06875         0.022000    5.0
2609.06994         0.088329    9.0
2679.06975         0.060500   60.0
...                     ...    ...
2609.06915         0.108696   46.0
2229.07055         0.064000  310.0
3009.07044         0.086242    6.0
2879.06965              NaN    NaN
2569.06925         0.023333  328.0

[894 rows x 2 columns]
/home/ubuntu/data/y_mean_tp1_2017.hdf
            new_Lichen_mean   new_N
lon_lat
2459.07055         0.188276   127.0
1729.06844         0.023000    10.0
2419.06875         0.077273   149.0
2209.06865         0.106447    76.0
2609.06994         0.114768   646.0
...                     ...     ...
2629.06915         0.015000     8.0
1869.06855         0.137367  1238.0
2469.07065         0.201053    36.0
2609.06915         0.113125    48.0
2569.06925         0.076667     6.0

[916 rows x 2 columns]
/home/ubuntu/data/y_mean_tp1_2018.hdf
            new_Lichen_mean   new_N
lon_lat
1729.06844         0.026154    13.0
2419.06875         0.038000   102.0
2679.06975         0.122778     3.0
2609.06994         0.123336  1067.0
2479.06975         0.096452    26.0
...                     ...     ...
2629.06915         0.079091    11.0
1869.06855         0.182484  2234.0
2579.07105         0.069744   187.0
2609.06915         0.139351    77.0
2569.06925         0.030000   568.0

[854 rows x 2 columns]

In [5]:
print('Finished!')

Finished!